def svg(paths, s=14, cls=""):
    return f'<svg width="{s}" height="{s}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="{cls}">{paths}</svg>'
OK='<circle cx="12" cy="12" r="10"></circle><path d="m9 12 2 2 4-4"></path>'
XX='<circle cx="12" cy="12" r="10"></circle><path d="m15 9-6 6"></path><path d="m9 9 6 6"></path>'
def page(title, body, rootcls="space-y-6 overflow-x-hidden"):
    return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" href="https://app.anestesiaquestoes.com.br/_next/static/chunks/9722c7b98429328f.css"></head>
<body class="geist_a71539c9-module__T19VSG__variable geist_mono_8d43a2aa-module__8Li5zG__variable antialiased" style="margin:0">
<div class="min-h-screen bg-slate-50"><div class="min-h-screen overflow-x-hidden bg-[radial-gradient(1300px_circle_at_18%_0%,rgba(15,23,42,0.08),transparent_55%),radial-gradient(950px_circle_at_100%_20%,rgba(2,132,199,0.10),transparent_45%)]"><div class="flex min-h-screen"><div class="flex min-w-0 flex-1 flex-col overflow-x-hidden">
<header class="sticky top-0 z-30 overflow-hidden border-b border-slate-200/70 bg-white/85 backdrop-blur" style="padding-top:44px"><div class="flex items-center justify-between gap-3 px-4 py-4"><div class="flex items-center gap-3 min-w-0"><button class="inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 shadow-sm">{svg('<path d="M4 5h16"></path><path d="M4 12h16"></path><path d="M4 19h16"></path>',18)}</button><div class="min-w-0"><div class="text-xs text-slate-500 font-semibold">Área do Aluno</div><div class="text-lg font-black text-slate-900 truncate">{title}</div></div></div><div class="flex min-w-0 shrink-0 items-center gap-3"><div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-2xl bg-slate-900 text-sm font-bold text-white shadow-lg">MS</div></div></div></header>
<main class="min-w-0 flex-1 overflow-x-hidden"><div class="px-4 py-8"><div class="{rootcls}">{body}</div></div></main></div></div></div></div></body></html>'''
def opt(letter,text,state=""):
    if state=="ok": return f'<div class="flex items-start gap-2 rounded-xl border px-3 py-2 text-sm border-emerald-200 bg-emerald-50"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded-md text-[11px] font-black text-white bg-emerald-500">{letter}</span><span class="min-w-0 text-slate-700"><span class="block">{text}</span></span>{svg(OK,15,"ml-auto shrink-0 text-emerald-500")}</div>'
    if state=="bad": return f'<div class="flex items-start gap-2 rounded-xl border px-3 py-2 text-sm border-rose-200 bg-rose-50"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded-md text-[11px] font-black text-white bg-rose-500">{letter}</span><span class="min-w-0 text-slate-700"><span class="block">{text}</span></span>{svg(XX,15,"ml-auto shrink-0 text-rose-500")}</div>'
    return f'<div class="flex items-start gap-2 rounded-xl border px-3 py-2 text-sm border-slate-200 bg-white"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded-md text-[11px] font-black text-white bg-slate-300">{letter}</span><span class="min-w-0 text-slate-700"><span class="block">{text}</span></span></div>'
TEMA="Anestesia para Oftalmologia"
Q="(ME2-TRI4-2025) Você irá fazer um bloqueio periconal para realização de uma retinopexia e deseja acinesia completa do olho e da pálpebra. Com relação a este bloqueio, podemos afirmar:<br><br>I - o bloqueio do IV nervo craniano promove acinesia do músculo reto lateral.<br>II - o bloqueio do III nervo craniano promove acinesia do músculo reto medial.<br>III - o bloqueio do nervo abducente promove acinesia do músculo oblíquo superior.<br>IV - a acinesia do músculo orbicular é obtida pelo bloqueio do VII nervo craniano.<br>V - o nervo oculomotor é responsável pela inervação dos músculos reto superior e reto inferior."
COM="A regra mnemônica da musculatura ocular extrínseca resolve o bloco: o abducente inerva o reto lateral, o troclear o oblíquo superior, e o oculomotor todos os demais. I. Falsa. O IV par, troclear, inerva o oblíquo superior. O reto lateral é inervado pelo VI par. II. Verdadeira. O III par, oculomotor, inerva o reto medial, além dos retos superior e inferior, do oblíquo inferior e do elevador da pálpebra. III. Falsa. O abducente, VI par, inerva o reto lateral, e não o oblíquo superior. IV. Verdadeira. O orbicular do olho é inervado pelo facial, VII par, que está fora do cone. V. Verdadeira. O oculomotor inerva os retos superior e inferior, entre outros músculos."
caderno=f'''<div><div class="text-xs font-bold uppercase tracking-widest text-slate-500">Revisão</div><div class="mt-0.5 text-3xl font-black text-slate-900">Caderno de Erros</div><div class="mt-1 text-sm text-slate-500">As questões que você errou ficam aqui automaticamente. Acerte de novo para marcá-las como resolvidas.</div></div>
<div class="flex gap-2"><button class="flex items-center gap-2 rounded-2xl border px-4 py-2 text-sm font-semibold border-rose-300 bg-rose-50 text-rose-700">Pendentes<span class="rounded-full bg-rose-500/15 px-2 py-0.5 text-[11px] font-bold text-rose-600">39</span></button><button class="flex items-center gap-2 rounded-2xl border px-4 py-2 text-sm font-semibold border-slate-200 bg-white text-slate-600">Resolvidas<span class="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[11px] font-bold text-emerald-600">112</span></button></div>
<div class="space-y-3"><div class="rounded-2xl border border-slate-200 bg-white p-4"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><div class="flex flex-wrap items-center gap-1.5"><span class="rounded-full border border-slate-200 bg-slate-50 px-2 py-0.5 text-[10px] font-semibold text-slate-600">{TEMA}</span><span class="rounded-full bg-rose-500/10 px-2 py-0.5 text-[10px] font-bold text-rose-600">Errou 4×</span></div></div><button class="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl border border-slate-200 text-slate-500">{svg('<path d="m18 15-6-6-6 6"></path>',15)}</button></div><div class="mt-4 border-t border-slate-100 pt-4"><div class="space-y-4"><div class="text-sm leading-6 text-slate-800">{Q}</div><div class="space-y-1.5">{opt("A","Apenas a afirmativa I é falsa.","bad")}{opt("B","Apenas as afirmativas I e IV são falsas.")}{opt("C","Apenas as afirmativas III e V são falsas.")}{opt("D","Apenas as afirmativas I e III são falsas.","ok")}</div><div class="rounded-xl bg-slate-50 p-3"><div class="text-[11px] font-bold uppercase tracking-wide text-slate-500">Comentário</div><div class="mt-1 text-sm leading-6 text-slate-700"><p>{COM}</p></div></div></div><div class="mt-4 flex justify-end"><button class="inline-flex max-w-full items-center justify-center gap-2 rounded-2xl text-center font-semibold bg-white text-slate-900 border border-slate-200 shadow-sm h-12 px-5 text-sm gap-2">{svg(OK)}Marcar como resolvida</button></div></div></div></div>'''
open('caderno2.html','w',encoding='utf-8').write(page("Caderno de Erros",caderno)); print('ok')
